# Generated by Django 3.1.4 on 2021-01-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updates',
            new_name='updated',
        ),
    ]
